COMMIT;

CREATE INDEX FSI_MYPRODUCT_1 ON MYPRODUCT(NAME) INDEXTYPE IS CTXSYS.CONTEXT;
CREATE INDEX FSI_MYPRODUCT_2 ON MYPRODUCT(COMPONENT) INDEXTYPE IS CTXSYS.CONTEXT;
---CONTAINS функция полнотекстового поиска в Oracle.
SELECT * FROM MYPRODUCT
        WHERE CONTAINS(NAME, 'Умывалка') > 0;

SELECT * FROM MYPRODUCT
    WHERE CONTAINS(COMPONENT, 'малина и мед') > 0;

DROP INDEX FSI_MYPRODUCT_1;
DROP INDEX FSI_MYPRODUCT_2;
-----------------------------------------------POISK_MYPRODUCT_BY_COMPONENT---------------------------
CREATE OR REPLACE PROCEDURE POISK_MYPRODUCT_BY_COMPONENT(MY_COMPONENT IN VARCHAR2) 
  IS
    cursor MY_CURSOR (MY_COMPONENT VARCHAR2) IS
    SELECT * FROM MYPRODUCT
        WHERE CONTAINS(COMPONENT, MY_COMPONENT) > 0;
BEGIN
  FOR PEREMENAY IN MY_CURSOR(MY_COMPONENT) LOOP
    DBMS_OUTPUT.PUT_LINE(PEREMENAY.ID || ' - ' || PEREMENAY.NAME || ' ' || PEREMENAY.COST);
  END LOOP;
END;


BEGIN
 POISK_MYPRODUCT_BY_COMPONENT('малина');
END;
-----------------------------------------------POISK_MYPRODUCT_BY_NAME---------------------------
CREATE OR REPLACE PROCEDURE POISK_MYPRODUCT_BY_NAME(MY_NAME IN VARCHAR2) 
  IS
    cursor MY_CURSOR (MY_NAME VARCHAR2) IS
    SELECT * FROM MYPRODUCT
        WHERE CONTAINS(NAME, MY_NAME) > 0;
BEGIN
  FOR customer_rec IN MY_CURSOR(MY_NAME) LOOP
    DBMS_OUTPUT.PUT_LINE(customer_rec.ID || ' - ' || customer_rec.NAME || ' ' || customer_rec.COST);
  END LOOP;
END;


BEGIN
 POISK_MYPRODUCT_BY_NAME('Тоник');
END;