COMMIT;
CREATE TABLESPACE TS_FLORE
    DATAFILE 'TS_FLORE1.DBF' 
    SIZE 10M
    AUTOEXTEND ON NEXT 5M
    MAXSIZE 30M;
    
DROP TABLESPACE TS_FLORE;
-------------------------------------------------------------------------------------

CREATE ROLE ROLE_MANAGER;

GRANT ALL PRIVILEGES TO ROLE_MANAGER;

CREATE PROFILE PROFILE_MANAGER LIMIT PASSWORD_LIFE_TIME UNLIMITED;

CREATE USER CORE_MANAGER IDENTIFIED BY 123
PROFILE PROFILE_MANAGER
ACCOUNT UNLOCK
PASSWORD EXPIRE

ALTER USER CORE_MANAGER IDENTIFIED BY 123;
ALTER USER CORE_MANAGER QUOTA 30m ON TS_FLORE;

GRANT ROLE_MANAGER TO CORE_MANAGER;
GRANT DBA TO CORE_MANAGER;
GRANT CREATE USER TO CORE_MANAGER;
SELECT * FROM DBA_ROLE_PRIVS WHERE GRANTEE = 'CORE_MANAGER';

----------------------------
DROP USER CORE_MANAGER CASCADE;
DROP ROLE ROLE_MANAGER CASCADE;
DROP PROFILE PROFILE_MANAGER CASCADE;