commit;
CREATE ROLE ROLE_USER;

GRANT EXECUTE ON CORE_MANAGER.MYBACKET_DELETE_ROW TO ROLE_USER;
GRANT EXECUTE ON CORE_MANAGER.MYBACKET_INSERT_ROW TO ROLE_USER;
GRANT EXECUTE ON CORE_MANAGER.MYORDERING_DELETE_ROW TO ROLE_USER;
GRANT EXECUTE ON CORE_MANAGER.MYORDERING_INSERT_ROW TO ROLE_USER;
GRANT EXECUTE ON CORE_MANAGER.MYCUSTOMER_UPDATE_ROW TO ROLE_USER;
GRANT EXECUTE ON CORE_MANAGER.MYOPINION_INSERT_ROW TO ROLE_USER;
GRANT CREATE SESSION TO ROLE_USER;

CREATE PROFILE PROFILE_USER LIMIT PASSWORD_LIFE_TIME UNLIMITED;

CREATE USER CORE_USER IDENTIFIED BY 123
PROFILE PROFILE_USER
ACCOUNT UNLOCK
PASSWORD EXPIRE
---измент сразу пароль ALTER USER CORE_USER IDENTIFIED BY 123;

GRANT ROLE_USER TO CORE_USER;
SELECT * FROM DBA_ROLE_PRIVS WHERE GRANTEE = 'CORE_USER';

----------------------------
DROP USER CORE_USER;
DROP ROLE ROLE_USER;
DROP PROFILE PROFILE_USER;



-----------------------------------PROCEDURE--------------------------------------
EXECUTE CORE_MANAGER.MYBACKET_DELETE_ROW(61);

EXECUTE CORE_MANAGER.MYBACKET_INSERT_ROW(61,41,54);

EXECUTE CORE_MANAGER.MYORDERING_DELETE_ROW(91);
EXECUTE CORE_MANAGER.MYORDERING_INSERT_ROW(91,41,54,32,'23-05-05','доставлен');

EXECUTE CORE_MANAGER.MYCUSTOMER_UPDATE_ROW('1111','11110');
EXECUTE CORE_MANAGER.MYOPINION_INSERT_ROW(100,41,54,'XXXX');